/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmconsole;

import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author eMan
 */
public class ContainerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ContainerJFrame
     */
    
    static int accountNumber;
    
    final static String LOGINPAGE = "Log in Page";
    final static String SERVICEPAGE = "Service Page";
    final static String BALANCEPAGE = "Balance Page";
    final static String WITHDRAWALPAGE = "Withdrawal Page";
    final static String SUCCESSPAGE = "Success Page";
    final static String TRANSFERPAGE = "Transfer Page";
    
    static JPanel cards;
    
    public ContainerJFrame() {
        initComponents();
        
        LoginJPanel ljp = new LoginJPanel();
        ServiceJPanel sejp = new ServiceJPanel();
        BalanceJPanel bjp = new BalanceJPanel();
        WithdrawJPanel wjp = new WithdrawJPanel();
        SuccessJPanel sujp = new SuccessJPanel();
        TransferJPane tjp = new TransferJPane();
        
        cards = new JPanel(new CardLayout());        
        cards.add(new JScrollPane(ljp), LOGINPAGE);
        cards.add(new JScrollPane(sejp), SERVICEPAGE);
        cards.add(new JScrollPane(bjp), BALANCEPAGE);
        cards.add(new JScrollPane(wjp), WITHDRAWALPAGE);
        cards.add(new JScrollPane(sujp), SUCCESSPAGE);
        cards.add(new JScrollPane(tjp), TRANSFERPAGE);
        
        
        setContentPane(cards);
    }
    
    public static void setAccount(int accNo){
        accountNumber = accNo;
    }
    
    public static void frameClose(){
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
